title: Gregory Kelleher
intro: Dia Ḋuit, Gꞃéagóiꞃ is ainm dom agus fáilte go dtí mo ṡuíoṁ gꞃéasáin

# Avatar must be uploaded to theme "img" folder.
intro_avatar: avatar.svg
author:
  name: Gregory Kelleher
  email: 'gregory@gregorykelleher.com'
  footer: Gregory Kelleher 2020
  #footer2:

metadata:
    description: 'Personal website for Gregory Kelleher'

social: 
  - icon: send
    link: "mailto:gregory@gregorykelleher.com" 
  - icon: youtube
    link: "https://www.youtube.com/user/Spokkam/" 
  - icon: github
    link: "https://github.com/gregorykelleher"  
  - icon: dribbble
    link: "https://dribbble.com/GregoryKelleher"   
